# Generated by Django 4.1 on 2022-08-23 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cleint_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=6)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('joined_date', models.DateField()),
                ('last_updated', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('full_time', models.BooleanField(default=False)),
                ('total_hour_worked', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_commission_generated', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('joined_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('existing_customer', models.BooleanField(default=False)),
                ('amount_recieved', models.DecimalField(decimal_places=2, default=False, max_digits=8)),
                ('tips', models.DecimalField(decimal_places=2, max_digits=8)),
                ('lead', models.CharField(max_length=30)),
                ('review', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.client')),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.employee')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.service')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_recieved', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_worth', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commission_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_date', models.DateField()),
                ('record_created', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.client')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=False, max_digits=8)),
                ('paid', models.BooleanField(default=False)),
                ('note', models.TextField()),
                ('attachment', models.ImageField(upload_to='images')),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.employee')),
            ],
        ),
    ]
