# Generated by Django 4.1 on 2022-08-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_alter_transaction_lead_alter_transaction_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
