# Generated by Django 4.1 on 2022-08-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0003_alter_expense_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='total_commission_generated',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='total_hour_worked',
        ),
    ]
